apiVersion: v1
kind: Pod
metadata:
  name: web-app-ip-returner
spec:
  containers:
  - name: web-app-ip-returner
    image: michaelantt/k8sapp:latest
    ports:
    - containerPort: 5000
    livenessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1